name: yt-dlp
summary: A fork of youtube-dl with additional features and patches
description: |
      Download and play videos on your local system. Runs from the command
      line and with all the features and patches of youtube-dlc in addition
      to the latest youtube-dl.

# version: '1.0'
version: git
# adopt-info: yt-dlp

# The adopt-info field is used to specify that the snap should be installed
# using the package name specified, rather than a version number. This is useful
# if you want to distribute a snap that has a consistent package name, but the
# version number may change over time.

grade: stable
confinement: devmode
base: core20
architectures:
  - build-on: [arm64, armhf, amd64]

apps:
  yt-dlp:
    command: bin/yt-dlp
    plugs: [home, network, network-bind, removable-media]

parts:
  yt-dlp:
    plugin: python
    source: https://github.com/yt-dlp/yt-dlp.git
    # https://forum.snapcraft.io/t/git-error-while-building-snap/10130 advice
    # override-build: |
    #   snapcraftctl build
    #   snapcraftctl set-version $(git describe --tags)

# The override-build section is used to specify custom build instructions for
# the part. In this case, the snapcraftctl set-version command is used to set
# the version of the snap to the latest git tag, using the git describe --tags
# command. This means that the version number of the snap will be automatically
# updated based on the latest git tag when the snap is built.
# 
# It used to not build without the override-build section, but now it does
# which is weird.
