name: building youtube-dl using snapcraft
on:
  push:
    branches: [ main ]
    # tags: ['v*', 'pre*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: snapcore/action-build@v1

